all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=127.4.172.130;port=3306;dbname=rhess'
      username: adminN8HeLTv
      password: NfuxeleLElNy
      attributes: { export: tables }
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=127.4.172.130;port=3306;dbname=rhess'
      username: adminN8HeLTv
      password: NfuxeleLElNy